import React from "react"
import { ShapChart } from "./ShapChart"

interface ResultData {
  class_index: number
  probability: number
  patientName: string
  patientId: string
  shap_values: { feature: string; value: number }[]
}

interface PrintableReportProps {
  resultData: ResultData | null
  reportRef: React.RefObject<HTMLDivElement>
}

const CLASS_STATUS_MAP = {
  1: { text: "Normal", color: "#15803d" }, // text-green-700
  2: { text: "Suspect", color: "#ca8a04" }, // text-yellow-600
  3: { text: "Pathological", color: "#b91c1c" }, // text-red-700
}

export const PrintableReport: React.FC<PrintableReportProps> = ({ resultData, reportRef }) => {
  if (!resultData) return null

  const status = CLASS_STATUS_MAP[resultData.class_index as keyof typeof CLASS_STATUS_MAP]
  const probabilityPercent = (resultData.probability * 100).toFixed(2)

  return (
    // This component is positioned off-screen to be captured for the PDF
    <div
      ref={reportRef}
      style={{
        position: 'absolute',
        left: '-9999px',
        top: 'auto',
        width: '794px', // A4 width in pixels at 96 DPI
        height: 'auto',
        backgroundColor: 'white',
        padding: '32px',
        fontFamily: 'sans-serif',
      }}
    >
      <div>
        {/* Header */}
        <div style={{ textAlign: 'center', borderBottom: '2px solid #d1d5db', paddingBottom: '16px', marginBottom: '32px' }}>
          <h1 style={{ fontSize: '1.875rem', fontWeight: 'bold', color: '#1f2937' }}>Fetal Health Analysis Report</h1>
          <p style={{ fontSize: '0.875rem', color: '#6b7280' }}>Generated on: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Patient and Result Summary */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '32px', marginBottom: '32px' }}>
          {/* Patient Information */}
          <div>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '8px', color: '#374151' }}>Patient Information</h2>
            <div style={{ fontSize: '0.875rem' }}>
              <p>
                <strong>Name:</strong> {resultData.patientName}
              </p>
              <p>
                <strong>ID:</strong> {resultData.patientId}
              </p>
            </div>
          </div>

          {/* Analysis Result */}
          <div>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '8px', color: '#374151' }}>Analysis Result</h2>
            <div style={{ fontSize: '0.875rem' }}>
              <p>
                <strong>Status:</strong>{" "}
                <span style={{ fontWeight: 'bold', color: status.color }}>{status.text}</span>
              </p>
              <p>
                <strong>Confidence:</strong> {probabilityPercent}%
              </p>
            </div>
          </div>
        </div>

        {/* SHAP Chart Section */}
        <div style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '1.125rem', fontWeight: 600, borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '16px', color: '#374151' }}>
            Feature Impact on Prediction
          </h2>
          <div style={{ width: '100%', height: '400px' }}>
            {resultData.shap_values && (
              <ShapChart
                data={resultData.shap_values}
                isAnimationActive={false} // Disable animations for PDF rendering
              />
            )}
          </div>
        </div>

        {/* Footer */}
        <div style={{ textAlign: 'center', fontSize: '0.75rem', paddingTop: '16px', borderTop: '1px solid #e5e7eb', marginTop: '32px', color: '#9ca3af' }}>
          <p>
            <strong>Disclaimer:</strong> This report is generated by an AI model and is intended for informational
            purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.
          </p>
        </div>
      </div>
    </div>
  )
}